version: 2
models:
  -name: stg_customers
  description: customer stage table
  columns:
    - name: customer_id
  description: primary id of the model
  data tests:
    - unique
      not_null
  - name: customer_name
    description: name of the customer